version: '3.8'

services:
  postgres:
      image: postgres:13
      ports:
        - 5431:5432
      volumes:
        - pgdata:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=postgres


volumes:
  pgdata:
    driver: local